components:
  schemas:
    AccessDeniedExceptionResponseContent:
      description: The server response for authorization failure.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    BadRequestExceptionResponseContent:
      description: The server cannot process the request due to an apparent client error.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    CreateOutboundFragmentRequestContent:
      properties:
        fragment:
          description: The fragment to stage for outbound delivery. Without a mapping, the fragment must be < 5MB
            and the shape must match the Guide JSON format for the specified guide. With a mapping, the fragment
            must be < 4MB and the shape must match the source schema of the specified mapping.
        guideId:
          description: The ID of the Stedi guide for the outbound transaction setting. The guide must be configured
            to use fragments. You can find this ID on the **Guides** page in the Stedi portal.
          type: string
        mappingId:
          description: Specify a mapping id to transform the fragment to Stedi's Guide JSON format.
          type: string
      required:
      - fragment
      - guideId
      type: object
    CreateOutboundFragmentResponseContent:
      properties:
        createdAt:
          description: The time Stedi created the fragment.
          format: date-time
          type: string
        fragmentGroupId:
          description: The fragment group ID where you created and added the fragment.
          type: string
        fragmentId:
          description: A unique ID for the fragment Stedi created within the fragment group.
          type: string
      required:
      - createdAt
      - fragmentGroupId
      - fragmentId
      type: object
    ExceptionCause:
      properties:
        message:
          type: string
        name:
          type: string
        stack:
          type: string
      type: object
    GatewayTimeoutExceptionResponseContent:
      description: The server was acting as a gateway or proxy and did not receive a timely response from the upstream
        server.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    ResourceNotFoundExceptionResponseContent:
      description: The server response when the specified resource cannot be found after an API request passes authentication
        and authorization.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    ResourceUnderChangeExceptionResponseContent:
      properties:
        message:
          type: string
      required:
      - message
      type: object
    ServiceExceptionResponseContent:
      properties:
        exceptionCause:
          $ref: '#/components/schemas/ExceptionCause'
        message:
          type: string
      required:
      - message
      type: object
    ServiceUnavailableExceptionResponseContent:
      description: The server cannot handle the request due to technical reasons.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    ThrottlingExceptionResponseContent:
      description: The server response when usage plan or account-level throttling limits exceeded.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    UnauthorizedExceptionResponseContent:
      description: The server response when the authorizer failed to authenticate the caller.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
    UnprocessableEntityExceptionResponseContent:
      description: The request parameters do not match a previous request with the same idempotency key.
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - message
      type: object
  securitySchemes:
    httpApiKeyAuth:
      description: A [Stedi API Key](https://www.stedi.com/app/settings/api-keys) for authentication.
      in: header
      name: Authorization
      type: apiKey
info:
  contact:
    email: healthcare@stedi.com
  license:
    name: Proprietary
    url: https://stedi.com
  title: Stedi Healthcare Claims Claim acknowledgments Fragments API
  version: '2025-03-07'
openapi: 3.0.3
paths:
  /fragments/{fragmentGroupId}:
    post:
      description: This endpoint stages a fragment for outbound delivery.
      operationId: CreateOutboundFragment
      parameters:
      - description: A unique ID for a group of fragments on Stedi. Stedi creates a new fragment group if one does
          not exist with the specified ID.
        examples:
          CreateOutboundFragment_example1:
            description: ''
            summary: Stage fragment
            value: fragmentGroup-02-21-2024
        in: path
        name: fragmentGroupId
        required: true
        schema:
          description: A unique ID for a group of fragments on Stedi. Stedi creates a new fragment group if one
            does not exist with the specified ID.
          type: string
      - description: A unique string to identify this request to the server. The key can be up to 255 characters.
          You can safely retry requests with the same idempotency key within 24 hours of making the first request.
          This prevents sending duplicate data to your trading partners in case of network errors or other intermittent
          failures. [Learn more](https://www.stedi.com/docs/api-reference/index#idempotency-keys).
        in: header
        name: Idempotency-Key
        schema:
          description: A unique string to identify this request to the server. The key can be up to 255 characters.
            You can safely retry requests with the same idempotency key within 24 hours of making the first request.
            This prevents sending duplicate data to your trading partners in case of network errors or other intermittent
            failures. [Learn more](https://www.stedi.com/docs/api-reference/index#idempotency-keys).
          type: string
      requestBody:
        content:
          application/json:
            examples:
              CreateOutboundFragment_example1:
                description: ''
                summary: Stage fragment
                value:
                  fragment:
                    baseline_item_data_PO1_loop:
                    - baseline_item_data_PO1:
                        assigned_identification_01: '123'
                        quantity_02: 3
                        unit_or_basis_for_measurement_code_03: XX
                        unit_price_04: 3
                    - baseline_item_data_PO1:
                        assigned_identification_01: '456'
                        quantity_02: 4
                        unit_or_basis_for_measurement_code_03: XX
                        unit_price_04: 4
                    - baseline_item_data_PO1:
                        assigned_identification_01: '789'
                        quantity_02: 5
                        unit_or_basis_for_measurement_code_03: XX
                        unit_price_04: 5
                    - baseline_item_data_PO1:
                        assigned_identification_01: '756'
                        quantity_02: 3
                        unit_or_basis_for_measurement_code_03: XX
                        unit_price_04: 3
                    - baseline_item_data_PO1:
                        assigned_identification_01: '432'
                        quantity_02: 4
                        unit_or_basis_for_measurement_code_03: XX
                        unit_price_04: 4
                    - baseline_item_data_PO1:
                        assigned_identification_01: '543'
                        quantity_02: 5
                        unit_or_basis_for_measurement_code_03: XX
                        unit_price_04: 5
                  guideId: 01HQ1XPE9C3SCEB2ND7VC53A8M
            schema:
              $ref: '#/components/schemas/CreateOutboundFragmentRequestContent'
        required: true
      responses:
        '201':
          content:
            application/json:
              examples:
                CreateOutboundFragment_example1:
                  description: ''
                  summary: Stage fragment
                  value:
                    createdAt: '2024-02-21T00:00:00Z'
                    fragmentGroupId: some-transaction-id
                    fragmentId: d3b3e3e3-3e3e-3e3e-3e3e-3e3e3e3e3e3e
              schema:
                $ref: '#/components/schemas/CreateOutboundFragmentResponseContent'
          description: CreateOutboundFragment 201 response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestExceptionResponseContent'
          description: BadRequestException 400 response
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedExceptionResponseContent'
          description: UnauthorizedException 401 response
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedExceptionResponseContent'
          description: AccessDeniedException 403 response
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundExceptionResponseContent'
          description: ResourceNotFoundException 404 response
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceUnderChangeExceptionResponseContent'
          description: ResourceUnderChangeException 409 response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnprocessableEntityExceptionResponseContent'
          description: UnprocessableEntityException 422 response
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingExceptionResponseContent'
          description: ThrottlingException 429 response
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceExceptionResponseContent'
          description: ServiceException 500 response
        '503':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableExceptionResponseContent'
          description: ServiceUnavailableException 503 response
        '504':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayTimeoutExceptionResponseContent'
          description: GatewayTimeoutException 504 response
      tags:
      - Fragments
security:
- httpApiKeyAuth: []
servers:
- description: Production
  url: https://core.us.stedi.com/2023-08-01
tags:
- name: Fragments
x-stedi:
  lifecycle: general_availability
  product: claims
  public: true
